### ISSUE TITLE
benefits over directly accessing the (undocumented) notion api?

### ISSUE THREAD

**Issue by dragonwocky** [splitbee/notion-api-worker#7]
This looks very interesting... what are the benefits of using this over directly accessing Notion's `loadPageChunk` or `getRecordValues` endpoints, though? That'd be nice to have documented somewhere.

**Comment by timolins** [comment]
Thanks for bringing this up. I think most benefits are listed in the features  section inside the README. Do you think we are missing something?

**Comment by dragonwocky** [comment]
You've said it's:

🍭 Easy to use – Receive Notion data with a single GET request
✨ Blazing Fast – Built-in SWR caching for instant results
🛫 CORS Friendly – Access your data where you need it
🗄 Table Access – Get structured data from tables & databases

The first three also apply to directly fetching the data from Notion from what I've tested.

I haven't fully compared the output yet, but it does look slightly different for tables, so I'm guessing the structured table access feature is referring to that. It would be nice to know what those differences are / have a comparison of some sort.

**Comment by tobiaslins** [comment]
Hi @dragonwocky!

The Notion API doesn't support CORS requests from other domains. So it can't be used from the client side directly.
We also added a caching layer to reduce latency.
For example:
`loadPageChunk` takes ~500-800ms on Notion directly. All requests on our side take only about ~60ms.

The table API also resolves user fields & more. You get a simple structured JSON array instead of a nested complicated array.

For `loadPageChunk` we also prefetch required blocks that are needed for collapsible blocks in Notion as well as inline tables.

**Comment by dragonwocky** [comment]
Great, thanks!
(Hadn't noticed those CORS restrictions as I'd mostly been accessing from the server-side.)
